### ISSUE TITLE
Azure AD with accessToken Connection lost - read ECONNRESET

### ISSUE THREAD

**Issue by rohit12sh** [tediousjs/tedious#1182]
I am working on an App that is authenticating user using Azure AD, extracting his `accessToken` and then using this token to connect to the Azure SQL server using below setting.

But unfortunately, I am getting `ESOCKET "Connection lost - read ECONNRESET"` right away,

```
const config = {
          server: 'db-server-name.database.windows.net',
          authentication: {
            type: 'azure-active-directory-access-token',
            options: {
              token: cloudAccessToken
            }
          },
          options: {
            debug: {
              packet: true,
              data: true,
              payload: true,
              token: false,
              log: true
            },
            database: 'DBNAME',
            encrypt: true,
            packetSize: 8192,
            keepAlive:true,
            requestTimeout: 300000,
            connectionTimeout: 32000,
          }
        };

        const connection = new Connection(config);

        connection.on('connect', function (err) {
          if (err) {
            console.log(err);
          }
          executeStatement();
        });

        connection.on('debug', function (text) {
          console.log(text);
        });

        connection.on('error', function (err) {
          console.error(err); // --> this gets trigger with error ESOCKET right away
        });;
```

**Comment by IanChokS** [comment]
hi @rohit12sh can you show a stack trace and what version of tedious you are using?

**Comment by rohit12sh** [comment]
@IanChokS 
tedious: 9.2.1
Stack:

```
State change: Connecting -> SentPrelogin
State change: SentPrelogin -> SentTLSSSLNegotiation
State change: SentTLSSSLNegotiation -> SentLogin7WithStandardLogin

ConnectionError: Connection lost - read ECONNRESET
    at ConnectionError (/node_modules/tedious/lib/errors.js:13:12)
    at Connection.socketError (/node_modules/tedious/lib/connection.js:1657:54)
    at Socket.<anonymous> (/node_modules/tedious/lib/connection.js:1417:14)
    at Socket.emit (events.js:228:7)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  message: 'Connection lost - read ECONNRESET',
  code: 'ESOCKET'
}

State change: SentLogin7WithStandardLogin -> Final
```

**Comment by rohit12sh** [comment]
Hi @lastonesky - any idea why `tedious` is not connecting using my Azure AD Token and `azure-active-directory-access-token` auth type option? I have added `trustServerCertificate: true` as well but no luck.

Same POC developed in Java using JDBC working fine using Azure AD token.

**Comment by rohit12sh** [comment]
Issue is resolved now. Removing `packetSize: 8192` from my config made the connection successful

**Comment by IanChokS** [comment]
Glad to hear you found the solution! Sorry for not being able to be of much help sooner 🙇

**Comment by zinvob** [comment]
This still does not work for Azure SQL. I have provided a fix.
